services:
  nextjs:
    container_name: resume-nextjs
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    image: resume-nextjs:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - traefik-net
    labels:
      - traefik.enable=true
      - traefik.http.routers.resume.rule=Host(`resume.${DOMAIN}`)
      - traefik.http.services.resume.loadbalancer.server.port=3000
      - traefik.http.routers.resume.entrypoints=websecure
      - traefik.http.routers.resume.tls=true
      - traefik.http.routers.resume.tls.certresolver=cloudflare
      - traefik.http.routers.resume.service=resume
      # Optional: Add middleware for security headers
      - traefik.http.middlewares.secHeaders.headers.browserXssFilter=true
      - traefik.http.middlewares.secHeaders.headers.contentTypeNosniff=true
      - traefik.http.middlewares.secHeaders.headers.forceSTSHeader=true
      - traefik.http.middlewares.secHeaders.headers.stsIncludeSubdomains=true
      - traefik.http.middlewares.secHeaders.headers.stsPreload=true
      - traefik.http.middlewares.secHeaders.headers.stsSeconds=31536000
      - traefik.http.routers.resume.middlewares=secHeaders

networks:
  traefik-net:
    external: true