# compose.yaml
version: '3'

services:
  nextjs:
    container_name: resume-nextjs
    build:
      context: .
      dockerfile: Dockerfile.nextjs
    restart: unless-stopped
    image: resume-nextjs:latest
    environment:
      - NODE_ENV=production
    networks:
      - internal

  nginx:
    container_name: resume-nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    restart: unless-stopped
    image: resume-nginx:latest
    networks:
      - internal
      - traefik-net
    depends_on:
      - nextjs
    labels:
      - traefik.enable=true
      - traefik.http.routers.resume.rule=Host(`resume.${DOMAIN}`)
      - traefik.http.services.resume.loadbalancer.server.port=80
      - traefik.http.routers.resume.entrypoints=websecure
      - traefik.http.routers.resume.tls=true
      - traefik.http.routers.resume.tls.certresolver=cloudflare
      - traefik.http.routers.resume.service=resume

networks:
  internal:
    name: resume_internal
  traefik-net:
    external: true