# Dockerfile.nginx
FROM nginx:alpine

# Copy custom Nginx configuration
COPY nginx/nextjs.conf /etc/nginx/conf.d/default.conf

# Expose port 80
EXPOSE 80

# Command to run Nginx in foreground
CMD ["nginx", "-g", "daemon off;"]