import type { Metadata } from "next";
import { Roboto, Roboto_Mono } from "next/font/google";
import "./globals.css";
import Nav from "@/ui/home/Nav";
import ThemeProvider from "@/ui/ThemeProvider";
import background from "@/public/background.jpg";

const RobotoSans = Roboto({
    variable: "--font-roboto-sans",
    subsets: ["latin"],
});

const RobotoMono = Roboto_Mono({
    variable: "--font-roboto-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Kim-Resume",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${RobotoSans.variable} ${RobotoMono.variable} antialiased relative overflow-x-hidden`}
            >
                <div
                    className="inset-0 z-[-1] bg-cover bg-center bg-no-repeat"
                    style={{
                        backgroundImage: `linear-gradient(rgba(var(--overlay-color), 0.8), rgba(var(--overlay-color), 0.8)), url(${background.src})`,
                    }}
                >
                    <div className="bg-transparent">
                        <div className="container mx-auto p-4">
                            <ThemeProvider>
                                <Nav />
                            </ThemeProvider>
                        </div>
                    </div>
                    <div className="container mx-auto">
                        <ThemeProvider>{children}</ThemeProvider>
                    </div>
                </div>
            </body>
        </html>
    );
}
